"""insert image_info table

Revision ID: 02b6086d9532
Revises: d42f2eb8c09d
Create Date: 2021-07-14 19:55:17.590108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02b6086d9532'
down_revision = 'd42f2eb8c09d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_info',
    sa.Column('image_pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_pk', sa.Integer(), nullable=True),
    sa.Column('s3_path', sa.String(length=150), nullable=True),
    sa.Column('time_reccord', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['video_pk'], ['video_info.video_pk'], ),
    sa.PrimaryKeyConstraint('image_pk'),
    sa.UniqueConstraint('s3_path')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_info')
    # ### end Alembic commands ###
