"""Initial migration.

Revision ID: 7b08a255667f
Revises: 
Create Date: 2021-07-11 14:52:33.058830

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b08a255667f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
    sa.Column('user_pk', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', sa.String(length=150), nullable=False),
    sa.Column('user_pw', sa.String(length=200), nullable=False),
    sa.Column('user_nick', sa.String(length=120), nullable=False),
    sa.Column('user_prof', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('user_pk'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('user_nick')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_info')
    # ### end Alembic commands ###
