"""empty message

Revision ID: af17dc9ab78e
Revises: 
Create Date: 2021-07-24 00:57:35.233283

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af17dc9ab78e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', sa.String(length=150), nullable=False),
    sa.Column('user_pw', sa.String(length=200), nullable=False),
    sa.Column('user_nick', sa.String(length=120), nullable=False),
    sa.Column('user_prof', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('user_nick')
    )
    op.create_table('video_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.Boolean(), nullable=False),
    sa.Column('video_title', sa.String(length=150), nullable=True),
    sa.Column('s3_title', sa.String(length=150), nullable=True),
    sa.Column('youtube_url', sa.String(length=150), nullable=True),
    sa.Column('s3_video', sa.String(length=150), nullable=True),
    sa.Column('s3_audio', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_pk', sa.Integer(), nullable=True),
    sa.Column('s3_path', sa.String(length=150), nullable=True),
    sa.Column('time_reccord', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['video_pk'], ['video_info.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_path')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_info')
    op.drop_table('video_info')
    op.drop_table('user_info')
    # ### end Alembic commands ###
