"""Delete unique in s3

Revision ID: ce5c8a8b0784
Revises: 02b6086d9532
Create Date: 2021-07-15 13:00:20.548112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce5c8a8b0784'
down_revision = '02b6086d9532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('video_info_s3_audio_key', 'video_info', type_='unique')
    op.drop_constraint('video_info_s3_video_key', 'video_info', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('video_info_s3_video_key', 'video_info', ['s3_video'])
    op.create_unique_constraint('video_info_s3_audio_key', 'video_info', ['s3_audio'])
    # ### end Alembic commands ###
