"""insert nideo_info table

Revision ID: d42f2eb8c09d
Revises: 7b08a255667f
Create Date: 2021-07-14 19:31:54.197260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd42f2eb8c09d'
down_revision = '7b08a255667f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_info',
    sa.Column('video_pk', sa.Integer(), nullable=False),
    sa.Column('category', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('youtube_url', sa.String(length=150), nullable=True),
    sa.Column('s3_video', sa.String(length=150), nullable=True),
    sa.Column('s3_audio', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('video_pk'),
    sa.UniqueConstraint('s3_audio'),
    sa.UniqueConstraint('s3_video')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_info')
    # ### end Alembic commands ###
